@startuml
skinparam classAttributeIconSize 0

class Bundle {
  type: collection
}

' Relationships (references)
Bundle "1" o-left- "1" Task
Bundle "1" o-- "1" MedicationRequest
Bundle "1" o-- "1" MedicationDispense
Bundle "1" o-right- "*" VZDSearchBundle

MedicationRequest "1" --> "1" PrescribedMedication

MedicationDispense "1" --> "1" DispensedMedication

VZDSearchBundle "1" --> "1" HealthcareService
VZDSearchBundle "1" --> "1" Organization
VZDSearchBundle "1" --> "1" Location

@enduml
